### ISSUE TITLE
Large image with statsSync throws error

### ISSUE THREAD

**Issue by jboolean** [11ty/eleventy-img#156]
Image.statsSync throws the following error:

```
    ENAMETOOLONG: name too long, open '/Users/julianboilen/Repositories/woolard/ocf/data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBUIFRIWFRUYGBgaHBwdGhwcGB4YHRYjIRwZHB4cHRwcIS4lHB4sHxkZJkYmLC8xNTVDGiU7QDs0Py40NTEBDAwMEA8QHxISHzYrJSw2NDQ9NjU0MTQ3NjQ2Njc0NDQ0NDY0NDQ0NDQ0NDQ0NDQ0NDQ2NDQ0NDQ0NDQ0NDQ0Pf/AABEIAOEA4QMBIgACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAABgcBBAUCAwj/xABAEAACAQICBwUFBgQGAgMAAAABAgADEQQFBhIhMUFRYQcicYGRExQyUqFCYnKCkrEVI6LBFjNTssLwQ9IlNET/xAAZAQEAAwEBAAAAAAAAAAAAAAAAAgMEAQX/xAAqEQACAgEDAwMDBQEAAAAAAAAAAQIRAxIhMQQiQRMyUWGB8FJxkbHhM/aAAwDAQACEQMRAD8AuaIiAIiIAiIgGInh2CAkkADaSdgHUyG55p9Rwl1oAVm+a9qY897eWzrJRhKTpIjKSXJNCbSO5lpnhMvuPae0YcKY1/K99UHoTKuzbPcRnBPtahK/IO6g/KN/ibnrOZNUOl/UyqWb4J5je0eo9xRoIo4F2LE/lXVA9TOHitMMbib3rlRyRVS3mBrfWcGJesONcIrc5PybVTM69b4q9VvxVHb9zNVnLbyT4m8RLEkiIDFdxtNinmFaj8Naqv4ajr+xmvEUDtYbSzG4a1sQ5HJgr382BP1ncwXaNXp/5tFHHNSaZ+usCfSQmJW8ON8o6pyXktzLdOcHjbBnNJuVQWH6gSoHiRJLTqLVAKkEHaCDcHwI3z8/Tcy3Na+VtrUajJxIBureKnunxtKZ9L+llscz8l8xIDknaEtWy4pdQ/OgJU+K7WXyv5ScUK6YhVZGVlYXDKQQw5gjYZknCUXui2Mk+D7xESJIREQBERAEREAREQBERAMTkZ7n1HJFvUbvH4VG1m8BwHU7Jz9LNKkyNdVbPWI2LwUfM9uHTeem+VPjcW+PdnqOXdt7H9hwA6DYJow4HPd8FU8lbLk6mf6TV88JDHVp8KYPd/Md7Hx2bNgE4sRN0YqKpFDbfIiIkjgiJt5XllTNn9nSXWbVLWJC7Ba+07N5A85xtLdg1InTyjJKmbNURCodFJ1WbVLWNiq7N467NonOq02oMyOpVlJDA7CCNhBhSTdHaZ5ie6NFsQyqqlmY2VVFyT0Anl1KEgggg2IOwgjeD1nThiIiAIiIAnSyXPK+StrUn7pN2Rtqt4jgeosf2nNicaTVM6nXBcujmk9HPRZe5UA71Njt6lT9peu8cQLyQT8+UqjUGVlYqym6sDYqeYI3Sz9D9MRmerRrkLW3K25av/q3TceHIYc2DT3R4L4ZL2ZNYiJmLRERAEREAREQDEi+mOky5GmqlmrMO6N4QbtZhy5DiR0M6OkecJklFqjbW3It7a7HcOg4k8gZS+Nxb493qVG1nc3Y/wBhyAFgBwsJowYdbt8FWSenZHzrVWrszsxZmN2Ym5YniZ5iJ6BnEREARPtgsFUx7BKSlmN7KLC9hc7yBunnE0GwrMjqVZTZlYWI4/sQfOctXQPdfBvQp0ajCy1dbVN9+o2q2zhtMmPZfTvUxTAd5UUD8zMSPVBPhl2FGkOXeyT/AD8MzMo4urFmt53I8UHOeOzXGDD4p6Z2e0Qgc9ZDrAfp1/SUZJaoST5X5/RZFU0yMZTiGoVaDqSWVlItvY3Fx53I63MnummjRzLFUfYAB6iO1RmJCqE9mFY2B2nW1ethyJkfzjCDIsxUsP5ftUrDopcE/pIcW+6JY2ldf2GDxLg2JpkAjf3u6LH80hkm9UXHyditmmV/obS9xbHYg6rHDUn1SNqljrWIPHYhF+Tzl6N4VcfXIqDXUJUdrk7SFYgkg3+KxnYwdE4XJ8Q4H+bVUXHyqyL6ayuPOe9B8lfGU8VVUhSytQQnbqltXXe3HVUiw47RJaqUpX9DiXC+5wMmyV80V31lp0qYvUqNew2XsANrNbbYdOYvzWtc23cLix9OEl2mmMTALTwNDZTp2aob7WbeAx4kfEeFyN2rNbJ9FiyHEYtjRw6jWN9jOOAA3qDu5ngNoMmsm2qXD4OOO9IjN5mSfFZbitILVEo+xw6KRSDkIqKNt9u0lt5baDz2SLg3lkZJkWqMxESRwQDb/u6IgFn6EaV/xIChWP8ANA7rH/ygDj94D138DJtPz3Tc0yrKSrKQQRsKkG4IPAgy4dENIRntLvWFVLBxz5MByNjs4EEcicGfDp7o8F+Od7MkkREzFwiIgGJ4dggJJAA2knYB1nuQrtHzj3SkKCnvVfi6IN/6j3fDWkoQcpJIjKVKyE6V52c8rswJ9ml1pjpxa3NiL+AUcJxYiepGKiqRlbt2IiJI4IiIB9cIzo6GkSH1l1CDY617La/Xnslo6ZaOHOKS1FAGIQbh9sbyl+d7kenG8qpHKEFTYggg8iNoPrLr0azlc8oLUFg42Ovytx8jvB5HneZeocotSXgtxpO0yn8pzKplFVatM2YXBBGxhxVhy2D0HESf0cFS0lVMbhQKWJRgWF+6WWxKPYbmGzXAuQ20HcPppNoOMzdqtBlR22srA6rnncbVJ47DffvvfT0SyjE6OYkLVUGnWUgsh1lDKCy32ArsDjaLHW5yM5wnHUnv+bHYxcXT4N3tByk5hh0rqpD0hrMDv1TbWB6rYHwDc5qNXbH5I1zdkAU+CVlt/Sok8ZQ4IIuDvkXy7JWw+GzHC27paoKXHuPTUrbnZiy+KmUxnsk/Dsm1vf0Pi2HQ5Nawt7uH/NbX9deedHsT/AsrFZxtszqD9oux1P1XXyMZFhBpDldGkWIBIUkfKlW9vNVHqJ70uw5zOpg8EndUk1Kltmoid0epJA6gSXLcX82c8Wvg5egWQHGMcZXGsWYlAw+Jr3aqR+K9vM8jN3SbMqGXPrYhveKqnWpUBsp0flZhxa32mudvdUC87mf5mmjuGLKACAEpLwLWsotyAF/BTKfoYevmzsVV6rsbsQpY3PFiNi+dhJwXqScpbI43pVLk2c6z2vnTXqtdb3VF2KvgvE9Tc9ZjJsjr50xFFLgfEzGyr0Lc+gBO3dJFlegLka+LdaKAXZQwLWG06zfCo697ynzz7SwUlGHwQ9lRUW1lurNz1TvUcdb4jv2cbtd9uP8AxFenzIi+PwbZfUek4symzWNxuBBB5EEHznwn0o0nxZbUV3baW1VLnqTa5858ZciB6iInQJvZLmb5NWSqm22xl+ZTbWXzt5EA8JoxONJqmE6L9weKTGolRDrKwDKeYM2JXPZpnOqWwrHYbvT/AHZR/u/VLGnl5IaZUa4y1KzMREgSPJOrtlGaQ5oc4xFWrfuk2Toq7F8LjvW5sZaOnWYe4YOrY2ap/LX819bz1A58pTc2dLDmRRml4PURE2FIiIgCIiAJv5Jm9TJaoqUz0dT8Lr8p/seHqDoRONJqmE6LxyPOaWd0w9M/iU/Eh5MP77jOpKDy7H1MtcVKTFXHow4qw3MvT+8tDRvTOjm2qlS1KrusT3XP3GPH7p28r75gy4HDeO6NEciezJZETMzlpHtF8vfK/eqZFk9szUjssVZVIA5WNx5Tq0sGtOpUq73cKLn7KqNijpcs3ixm3E6227OJUcbMsgo5pUR62s4QWVCbIOJJA2sTs3kjujZvvq47SfBZIuorISuwU6QBt0svdXzIndxNBMSrI6hlYWYEXBHIjiJrUcnw1G2rQorbdq01FvCwnU15DT8EArDHabMLL7HD3BF7hTyPA1T4d3ZwO2dulluXaKKPbMjVLXu4DueqoAdUdQPEmSfMKNTEIVpVBSY/a1NcgcdUEgX6m46GQHG6LLh2Yihi8Ux2lmdKaseZb4yZdGSltdL4RW46d+WaWkGmr40Gnhx7GmbgmwDMPLYg8NvUbpD5162jmMogk4apbout9FuZyiLTZjUEqiUScm9xERLDgiIgH3wOLbAVEqr8SMGHW28HoRcecvbBYlcYiVFN1dQw8CLiUFLR7M8w94w7UidtJtn4Xuw/q1x5CZeqja1fBbilvRNYmJmYLNBWfaljNeph6IOxVLkcyx1V8wFb9Ugs7um2J94xuIN9ilVHTVVQR+rWnCnqYVWNIyTdyYiIlpEREQBERAEREATBF5mIBIck0xxOVWUt7VB9lySR+F9487gcBJ3k2m2HzNlQh0qMQoUqWDE8mW+zq1pUcm3Znlft6r4hhspjVX8TDvHxCm355mz4oaXKiyE5XRZpYCwvvmZTWm+a/wAWxL2N0p3ROWw99h4sLX5Ks4RqsRbWa3K5t6SqPStpOyby0+C8Myz3D5WD7Wqqn5b6zHwVbt9JBM47QqlYlcOopr87AM56hfhXz1pBwLTMuh00Y87kJZZPg7J0rxx/Q3oo+gWbGG01x1A3NYOPlZFI9VAb6yPRLfTh8L+CGqXyd6vpfi6tU1VqFCbDUUkps+45YAnmJzM0zBs0qNVdUVmA1tVSoJAtrEEnaZqROqEVwg5N8iIiSOCIiAJKeznGe74wJfZUVltwuBrg+isPzSLTcyXE+6YjDve2rUQnw1gG/pJkMkdUGiUXTTL6ieZmeUarKEzap7WviD81Wo3qzH+81YZtYk8yTE9dKkYxEROgREQBERAEREAREQDBlpYo/4TywKDaqw1evtHuWI56o1iPwCQnQ7L/wCJYuipF1U+0bwSxHkX1R5zsdpmY+8V0og92mt2/E+3aOi6v6zM+Tvmofdlke2Ll9iFgWmYiaCsREQBERAEREAREQBERAE8vtBnqeYBcH+JRzESqvfGiUehEs9Rmsw1SRE2Mzp+xrV1+Wo6+jsP7TXlyKxEROgREQBERAEREARE8wCxuzHCCimJrtsBIUE8Ao1mPgSw/TIHmOMOYVatU73Zm28ATsHkLDyliV/AIbJwNzPTA63qm7eYVm/TKzmfF3SlP60WT2SQiImgrEREAREQBERAEREAREQBPM9Ty5sDAPv7s3KJZf+F/u/SJR60SehkJ0yw/u2NxItsLBh11lVifUn0nFk27UMJ7OvRqjc6FT4o1/Uhx+mQmTxSvGmRmqkxERLDgiIgCIiAIiIAnvD0DiXpoN7sqDxZgo/eeJ2NEKHt8bhV+9rfoVn/dZGTpNnUrdEt7UcQKdPC0RsBZmtyCKFA/r+krqTDtNr+0xSLwWkPVmcn6BZD5XgVQRLI7bEREuICIiAIiIAiIgCIiAIiIAmzleG97rUEtfXdFPgWAP0vNaSXs+wnvWNptwpq7n01B9XB8pCctMWzsVbSLfiZmZ5RroivaDl/vuDdgO9SIqDwFw3lqlj5CVHP0DVpiqpUi4IIIPEHYRKJzfLzlderRN+61gT9pd6nzUgzb0s+YlOaO9mpERNZSIiIAiIgCIiAJKOzqnr41D8qO30C/8AKReS/sxW+Lc8qL/76cqzf82Sh7kc/Tup7THYjkuoo8kQn6kzgTr6Wtr43FH75HoAP7TkSWPaC/ZHJe5iIiTOCIiAIiIAiIgCIiAIiIAlmdmGX+yo1axG2o1l/ClxcfmLD8olbUKDYlkRRdnYKo5kmw+pl7ZXgly2lTpLuRQt+dt5PUm585l6mdLT8luKNuzcmZiZmE0GJAe0vJ/aqmJUbUstTqpPdPkxI/N0k+nyxFFcQrIwDKwIYHcQRYg+UlCbjJMjKNqj8/xOlpBlDZLXek1yu9GP2lO4+I3HqD0nNnqppq0ZWqERE6cEREAREQBLB7LsALV65Jvf2QHkjseu9fQyvpaHZe2thao5Vm/2UzKOpbUCeP3HH7QtHfdmOKp3Ks38wb9RjsDDoTstwJHPZB5fmNwq41HpuLq6lWHQi2zl4yisbhWwFSpTb4kYqeF7G1x0I2+ch02TUtL8EssadnwiImoqEREAREQBERAEREARE2MuwL5lUSkguzmw5LzY9ALnynG63BLuzbJ/eKjYhh3UuqdWI2n8qm35uks+aWVYBMspJSQd1BbqTvJPUkk+c3RPLyz1ys1wjpVGYiJAkIiIBHtLMgGe0bCwqLc02PPipPytYDpYHbaU5VptQZkZSrKSGB3qRsIM/Qchem+i38TBr0V/nKO8o/8AKB/zA3cxs5W04M2ntlwVZIXuirogi0TeZxERAEREASweyvE/Zp/gceesrfssr6STQHHDBYymCbCoDTPibMv9SgfmlWZXjaJQdSRcMqjtKwXu+KWoBsqoCerJ3T/AE6kteQLtUpg08M/EOyjwZbn/YJi6d1kRoyK4lbxET0jKIiIAiIgCIiAIieYB6lsaDaOfwhDUqD+c42j/TXeF8TsJ8hwueRoJooQVxNdeRpIRu5Ow58h58rWJMPUZr7Yl+OFbszERMpcIiIAiIgCIiAQjTDQ8ZlrVqAAq72XcKvW+4P13HjzlYuhpkqwKsDYgggqRvBB2gz9CSOaS6K0s9Gt8FUDY4G/ow+0PqOB3g6cOfT2y4KZ473RTsTezbKK2Ttq1l1flYbVf8LcfDYRxAmjNyaatFDVCIidAhHNMhlJBBBBG8EbQR1BiIBd2jWcLnVBKgtrbnUfZYbx4HeOhEhPafmAq1KNBTfUBZ+ha2qPEKCfzCRLLc0rZUzNQqFCws1gCGHC6sCDa5222XPOa1aq1dmd2LMxJYk3JJ4kzNDp9OTV4LJZLjR5iImkrEREAREQBETYy/AVMycJSQux4Dco5sdyjqZxuga8sHQ/QsgrXxS9UpEbuTOOf3fXkOtovobTyi1SqRUrcD9mn+EHeep8gNt5dMWbqL7Y/wAl8MfliZiJlLhERAEREAREQBERAEREA1sXhExqMlRFdTvDC4P/AHnIDnnZ6Vu2Fa4/03P0Vz+zfqljRJwySjwRlFS5KBxuDqYB9SqjI3Jha/UHcw6jZPhL9xeETGKVqIrqeDKGHoZE8y7PcPiNtFnonl8a+jHW9GmqPVJ+7Yplifgq6JKcdoFjMNfVCVRw1W1W81ewHgCZwsVlGIwl9ehUW3Eo2r+oC31miOSEuGQcWuUacTyGB4iJMieonmCwHEQD1E2cNl1bF29nRqNfiqMw9QLCdzBaDY3E21kSmObuP2TWPraQlkjHlnVFvhEanuhQbEsFRWdjuVQWJ8hLIy3s6o0rGvUeoflX+WvgbEsfEESW4DLaWWrq0qaoOOqLE9Sd7HqZRPqUvbuWRxN8le5H2f1MRZsSfZr8ikMx8W2qPqfCWFluW0srQJSQIvTeTzJO1j1M3YmSeSU+S6MFHgzERIEhERAEREAREQBERAEREAREQBERAExMxOMCeZmJ04yL6U8fCVXjviiJ6OD2mefJ88N8Qll6I/Y8oiM3ByHJNJmZiecaUYiZiDoiIgCIiAIiIAiIgCIiAf/Z'
        at Object.openSync (fs.js:497:3)
        at syncFileToBuffer (/Users/julianboilen/Repositories/woolard/ocf/node_modules/@11ty/eleventy-img/node_modules/image-size/dist/index.js:84:27)
        at imageSize (/Users/julianboilen/Repositories/woolard/ocf/node_modules/@11ty/eleventy-img/node_modules/image-size/dist/index.js:123:24)
        at Function.statsSync (/Users/julianboilen/Repositories/woolard/ocf/node_modules/@11ty/eleventy-img/img.js:548:22)
        at Object.image (/Users/julianboilen/Repositories/woolard/ocf/src/_data/image.js:41:26)
        at eval (./src/home/team.ejs:54:17)
```

**Comment by jboolean** [comment]
Nevermind, I think I had some bad data.

**Comment by zeroby0** [comment]
Not a bad idea, you just implemented [RFC 1776](https://datatracker.ietf.org/doc/html/rfc1776)! 😆
