### ISSUE TITLE
TypeError: callback.call is not a function

### ISSUE THREAD

**Issue by sdcaulley** [11ty/eleventy-img#94]
I have been working thorough the synchronous example posted at https://www.11ty.dev/docs/plugins/image/.  However, I continue to get an error:
```
TypeError: callback.call is not a function
        at Object.<anonymous> (/home/stephanie/Programming/bl-website/node_modules/@11ty/eleventy/src/BenchmarkGroup.js:30:26)
        at /home/stephanie/Programming/bl-website/src/_includes/layouts/block-page.11ty.js:29:18
        at Array.map (<anonymous>)
        at Object.exports.render (/home/stephanie/Programming/bl-website/src/_includes/layouts/block-page.11ty.js:25:29)
        at JavaScript.<anonymous> (/home/stephanie/Programming/bl-website/node_modules/@11ty/eleventy/src/Engines/JavaScript.js:129:43)
        at TemplateLayout.render (/home/stephanie/Programming/bl-website/node_modules/@11ty/eleventy/src/TemplateLayout.js:152:31)
        at async Template.renderPageEntry (/home/stephanie/Programming/bl-website/node_modules/@11ty/eleventy/src/Template.js:603:17)
        at async Template.writeMapEntry (/home/stephanie/Programming/bl-website/node_modules/@11ty/eleventy/src/Template.js:616:21)
        at async Promise.all (index 4)
        at async Eleventy.write (/home/stephanie/Programming/bl-website/node_modules/@11ty/eleventy/src/Eleventy.js:743:13)
```
Stack is:
Node.js - 14.15.4
11ty.js - 0.12.1
@11ty/eleventy-img - 0.8.3

Any help would be appreciated.

**Comment by dheimoz** [comment]
hello @sdcaulley have you found the solution? Do you mind sharing it for the community? Open Source Software is enhanced by sharing information.
